// Project
import './project/b33.jpg';
import './project/b33_plan.jpg';
import './project/h33.jpg';
import './project/h33_plan.jpg';
import './project/h52.jpg';
import './project/h52_plan.jpg';
import './project/h64.jpg';
import './project/h64_plan.jpg';

// Portfolio
import './portfolio/1.jpg';
import './portfolio/2.jpg';
import './portfolio/3.jpeg';
import './portfolio/3.jpg';
import './portfolio/4.jpg';
import './portfolio/5.jpg';
import './portfolio/6.jpg';
import './portfolio/7.jpg';
import './portfolio/8.jpg';
import './portfolio/9.jpg';
import './portfolio/10.jpg';
import './portfolio/11.jpg';
import './portfolio/12.jpg';
import './portfolio/13.jpg';
import './portfolio/14.jpg';
import './portfolio/15.jpg';
import './portfolio/16.jpg';
import './portfolio/17.jpg';
import './portfolio/18.jpg';
import './portfolio/19.jpg';
import './portfolio/20.jpg';
